name: Test published packages

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  test_package:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ ubuntu-latest, windows-2019, macos-13 ]
        node-version: [ 16.x, 18.x, 20.x, 21.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install 
    - run: npx @mapbox/node-pre-gyp install --update-binary
    - run: npx yatag
    - run: npm test
